src/Testura.Code.Tests/Integration/ModelClassTests.cs, src/Testura.Code.Tests/Integration/NunitTest.cs, src/Testura.Code.Tests/Statements/DeclarationStatementTests.cs, src/Testura.Code.Tests/Statements/StatementTests.cs, src/Testura.Code.Tests/Testura.Code.Tests.csproj, src/Testura.Code/Generators/Class/ConstructorGenerator.cs, src/Testura.Code/Generators/Class/FieldGenerator.cs, src/Testura.Code/Generators/Class/PropertyGenerator.cs, src/Testura.Code/Statements/DeclarationStatement.cs, src/Testura.Code/Statements/Statement.cs, src/Testura.Code/Testura.Code.csproj
Fixed the spelling of the DeclarationStatement class and all associated references
=> Corrected the spelling of Declaration throughout the solution

README.md, src/Testura.Code.Tests/Generators/Class/PropertyGeneratorTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ParenthesizedLambdaArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ValueArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/GenericGeneratorTests.cs, src/Testura.Code.Tests/Integration/HelloWorldTest.cs, src/Testura.Code.Tests/Integration/ModelClassTests.cs, src/Testura.Code.Tests/Integration/NunitTest.cs, src/Testura.Code/Factories/EqualsValueClauseFactory.cs, src/Testura.Code/Generators/Class/PropertyGenerator.cs, src/Testura.Code/Generators/Common/ArgumentGenerator.cs, src/Testura.Code/Generators/Common/ReferenceGenerator.cs, src/Testura.Code/Generators/Special/NunitAssertGenerator.cs, src/Testura.Code/Models/Field.cs, src/Testura.Code/Models/Invocation.cs, src/Testura.Code/Models/Properties/Property.cs, src/Testura.Code/Models/References/VariableReference.cs, src/Testura.Code/Properties/AssemblyInfo.cs, src/Testura.Code/Statements/DeclarationStatement.cs, src/Testura.Code/Statements/ExpressionStatement.cs, src/Testura.Code/Statements/JumpStatement.cs
=> Release 0.2.1

src/Testura.Code.Tests/Generators/Common/BinaryExpressions/AndBinaryExpressionTest.cs, src/Testura.Code.Tests/Generators/Common/BinaryExpressions/ConditionalBinaryExpressionTests.cs, src/Testura.Code.Tests/Generators/Common/BinaryExpressions/MathBinaryExpressionTests.cs, src/Testura.Code.Tests/Generators/Common/BinaryExpressions/OrBinaryExpressionTest.cs, src/Testura.Code.Tests/Statements/DeclarationStatementTests.cs, src/Testura.Code.Tests/Statements/ExpressionStatementTests.cs, src/Testura.Code.Tests/Statements/IterationStatementTests.cs, src/Testura.Code.Tests/Statements/SelectionStatementTests.cs, src/Testura.Code.Tests/Testura.Code.Tests.csproj, src/Testura.Code/Enums.cs, src/Testura.Code/Factories/ConditionalFactory.cs, src/Testura.Code/Factories/EqualsValueClauseFactory.cs, src/Testura.Code/Factories/MathOperatorFactory.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/BinaryExpressionArgument.cs, src/Testura.Code/Generators/Common/BinaryExpressions/AndBinaryExpression.cs, src/Testura.Code/Generators/Common/BinaryExpressions/ConditionalBinaryExpression.cs, src/Testura.Code/Generators/Common/BinaryExpressions/IBinaryExpression.cs, src/Testura.Code/Generators/Common/BinaryExpressions/MathBinaryExpression.cs, src/Testura.Code/Generators/Common/BinaryExpressions/OrBinaryExpression.cs, src/Testura.Code/Properties/AssemblyInfo.cs, src/Testura.Code/Statements/DeclarationStatement.cs, src/Testura.Code/Statements/IterationStatement.cs, src/Testura.Code/Statements/SelectionStatement.cs, src/Testura.Code/Testura.Code.csproj
- Added methods to generate foreach loop
- Added methods to generate while loop 
- Added Support for binary expressions: 
- Conditional binary expressions (for example 1 == 2)
- "Or" and "and" (for example 1 == 2 || 2 == 2)
- Math (for example 1 + 1)
- Added declare and assign methods that accept binary expressions 
- Added BinaryExpressionArgument
=> Release 0.3.0

README.md, src/Testura.Code.Tests/Compilation/CompilerTests.cs, src/Testura.Code/Compilations/Compiler.cs, src/Testura.Code/Compilations/ICompiler.cs, src/Testura.Code/Properties/AssemblyInfo.cs
- Added methods to compile code in memory without creating a dll
=> Release 0.3.1

src/Testura.Code.Tests/Generators/Common/TypeGeneratorTests.cs, src/Testura.Code.Tests/Statements/JumpStatementTests.cs, src/Testura.Code/Generators/Common/TypeGenerator.cs, src/Testura.Code/Models/Types/CustomType.cs, src/Testura.Code/Properties/AssemblyInfo.cs, src/Testura.Code/Statements/JumpStatement.cs, src/Testura.Code/Testura.Code.csproj
- It's now possible to use custom/undefined types with CustomType.Create()
- New jump statement method to return "this"
=> Release 0.4.0

src/Testura.Code/Properties/AssemblyInfo.cs, src/Testura.Code/Util/AppDomains/AppDomainCodeGenerator.cs
- You can now set evidence and permission for the created app domain in AppDomainCodeGenerator
=> Release 0.5.1

src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/LambdaArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ParenthesizedLambdaArgumentTests.cs, src/Testura.Code.Tests/Testura.Code.Tests.csproj, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/LambdaArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ParenthesizedLambdaArgument.cs, src/Testura.Code/Properties/AssemblyInfo.cs, src/Testura.Code/Testura.Code.csproj
- New class for simple lambda arguments 
- ParenthesizedLambdaArgument now also accept blocksyntax
=> Release 0.5.2

src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ArrayInitializeArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ClassInitializationArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/DictionaryArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/InvocationArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/LambdaArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ParenthesizedLambdaArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ReferenceArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/TypeOfArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ValueArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/VariableArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/TypeGeneratorTests.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/Argument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ArrayInitializationArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/BinaryExpressionArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ClassinitializationArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/DictionaryInitializationArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/InvocationArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/LambdaArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ParenthesizedLambdaArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ReferenceArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/TypeOfArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ValueArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/VariableArgument.cs, src/Testura.Code/Generators/Common/TypeGenerator.cs, src/Testura.Code/Properties/AssemblyInfo.cs, src/Testura.Code/Testura.Code.csproj
- All arguments can now be generated as "named arguments". 
- Improved how we generate nullables for predefined types and enums
=> Release 0.6.0

src/Testura.Code.Tests/Generators/Class/FieldGeneratorTests.cs, src/Testura.Code.Tests/Generators/Common/AttributeGeneratorTests.cs, src/Testura.Code/Generators/Class/FieldGenerator.cs, src/Testura.Code/Generators/Common/AttributeGenerator.cs, src/Testura.Code/Models/Field.cs, src/Testura.Code/Models/Properties/Property.cs, src/Testura.Code/Properties/AssemblyInfo.cs
- Added support for attributes on fields
- Fixed named arguments in attributes
=> Release 0.7.0

src/Testura.Code.Tests/Builders/ClassBuilderTests.cs, src/Testura.Code.Tests/Builders/InterfaceBuilderTests.cs, src/Testura.Code.Tests/Builders/MethodBuildersTest.cs, src/Testura.Code.Tests/Testura.Code.Tests.csproj, src/Testura.Code/Builders/ClassBuilder.cs, src/Testura.Code/Builders/InterfaceBuilder.cs, src/Testura.Code/Builders/MethodBuilder.cs, src/Testura.Code/Builders/TypeBuilderBase.cs, src/Testura.Code/Testura.Code.csproj, src/Testura.Code/Testura.Code.nuspec, src/Testura.Code/packages.config
- Added interface builder
- Changed method builder so it add a semicolon if you set body to null
=> Release 0.11.0

src/Testura.Code.Tests/Generators/Common/ModifierGeneratorTests.cs, src/Testura.Code/Enums.cs, src/Testura.Code/Generators/Common/ModifierGenerator.cs
=> Added missing modifiers (internal and partial).

src/Testura.Code.Tests/Builders/NamespaceBuildersTest.cs, src/Testura.Code.Tests/Generators/Common/EnumGeneratorTests.cs, src/Testura.Code.Tests/Integration/ModelClassTests.cs, src/Testura.Code/Builders/Base/BuilderBase.cs, src/Testura.Code/Builders/Base/TypeBuilderBase.cs, src/Testura.Code/Builders/BuildMembers/ClassBuildMember.cs, src/Testura.Code/Builders/BuildMembers/ConstructorBuildMember.cs, src/Testura.Code/Builders/BuildMembers/EnumBuildMember.cs, src/Testura.Code/Builders/BuildMembers/EnumMember.cs, src/Testura.Code/Builders/BuildMembers/FieldBuildMember.cs, src/Testura.Code/Builders/BuildMembers/MethodBuildMember.cs, src/Testura.Code/Builders/BuildMembers/PropertyBuildMember.cs, src/Testura.Code/Builders/BuildMembers/RegionBuildMember.cs, src/Testura.Code/Builders/BuilderHelpers/MemberHelper.cs, src/Testura.Code/Builders/BuilderHelpers/NamespaceHelper.cs, src/Testura.Code/Builders/BuilderHelpers/UsingHelper.cs, src/Testura.Code/Builders/ClassBuilder.cs, src/Testura.Code/Builders/InterfaceBuilder.cs, src/Testura.Code/Builders/NamespaceBuilder.cs, src/Testura.Code/Builders/RegionBuilder.cs, src/Testura.Code/Builders/TypeBuilderBase.cs, src/Testura.Code/Generators/Common/EnumGenerator.cs, src/Testura.Code/Generators/Common/ReferenceGenerator.cs, src/Testura.Code/Models/EnumMember.cs
=> Added support for enum (as generator and in class builder)

src/Testura.Code.Tests/Generators/Common/TypeGeneratorTests.cs, src/Testura.Code/Generators/Common/TypeGenerator.cs
=> Added support for structs in type generator

src/Testura.Code.Tests/Generators/Class/PropertyGeneratorTests.cs, src/Testura.Code.Tests/Generators/Common/ModifierGeneratorTests.cs, src/Testura.Code/Enums.cs, src/Testura.Code/Generators/Class/PropertyGenerator.cs, src/Testura.Code/Generators/Common/ModifierGenerator.cs, src/Testura.Code/Models/Properties/AutoProperty.cs, src/Testura.Code/Models/Properties/BodyProperty.cs, src/Testura.Code/Models/Properties/Property.cs, src/Testura.Code/Testura.Code.csproj
- Added support for get and set modifiers and added the protected modifier #53
=> Added support for get and set modifiers and added the protected modifier

src/Testura.Code.Tests/Integration/ModelClassTests.cs, src/Testura.Code/Builders/Base/TypeBuilderBase.cs, src/Testura.Code/Builders/ClassBuilder.cs, src/Testura.Code/Builders/InterfaceBuilder.cs, src/Testura.Code/Builders/MethodBuilder.cs, src/Testura.Code/Enums.cs, src/Testura.Code/Extensions/CsharpSyntaxNodeExtensions.cs, src/Testura.Code/Extensions/StatementSyntaxExtension.cs, src/Testura.Code/Extensions/StatementSyntaxExtensions.cs, src/Testura.Code/Generators/Class/ConstructorGenerator.cs, src/Testura.Code/Generators/Class/FieldGenerator.cs, src/Testura.Code/Generators/Class/PropertyGenerator.cs, src/Testura.Code/Models/ConstructorInitializer.cs, src/Testura.Code/Models/Field.cs, src/Testura.Code/Models/Properties/AutoProperty.cs, src/Testura.Code/Models/Properties/BodyProperty.cs, src/Testura.Code/Models/Properties/Property.cs, src/Testura.Code/Testura.Code.csproj
- Added support for xml documentation to class, constructot, fields and properties.
- Added support for single line comments to statements.
=> Release 0.16.0

TesturaMutationBaseConfig.json, src/Testura.Code.Tests/Builders/InterfaceBuilderTests.cs, src/Testura.Code.Tests/Builders/MethodBuildersTest.cs, src/Testura.Code.Tests/Integration/ModelClassTests.cs, src/Testura.Code/Builders/Base/TypeBuilderBase.cs, src/Testura.Code/Builders/BuildMembers/MethodBuildMember.cs, src/Testura.Code/Builders/MethodBuilder.cs, src/Testura.Code/Enums.cs, src/Testura.Code/Factories/OperatorFactory.cs, src/Testura.Code/Testura.Code.csproj
- Added support for operator overloading #65 
- Fixed bug with ThatInheritFrom #64
=> Added support for operator overloading and fixed bug with ThatInheritFrom

src/Testura.Code.Tests/Statements/ExpressionStatementTests.cs, src/Testura.Code.Tests/Statements/JumpStatementTests.cs, src/Testura.Code/Statements/ExpressionStatement.cs
- Added support for object creation expression
=> Added support for object creation expression

src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/AssignArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ObjectCreationArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/Arguments/ArgumentTypes/ValueArgumentTests.cs, src/Testura.Code.Tests/Generators/Common/AttributeGeneratorTests.cs, src/Testura.Code.Tests/Generators/Common/ObjectCreationTests.cs, src/Testura.Code.Tests/Statements/ExpressionStatementTests.cs, src/Testura.Code.Tests/Statements/JumpStatementTests.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/AssignArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ObjectCreationArgument.cs, src/Testura.Code/Generators/Common/Arguments/ArgumentTypes/ObjectInitializationArgument.cs, src/Testura.Code/Generators/Common/BinaryExpressions/MathBinaryExpression.cs, src/Testura.Code/Generators/Common/ObjectCreationGenerator.cs, src/Testura.Code/Statements/ExpressionStatement.cs
- Added `AssignArgument` type 
- Changed name on `ClassInitializeArgument` to `ObjectCreationArgument`
- Fixed spelling errors in the `MathBinaryExpression` class
=> Added new attribute for assignment

src/Testura.Code.Tests/Generators/Class/PropertyGeneratorTests.cs, src/Testura.Code/Generators/Class/PropertyGenerator.cs, src/Testura.Code/Models/Properties/ArrowExpressionProperty.cs
- Added code to generate arrow expression property
=> Added code to generate arrow expression property

src/Testura.Code.Tests/Statements/ExceptionHandlingStatementTests.cs, src/Testura.Code.Tests/Statements/ExpressionStatementTests.cs, src/Testura.Code/Models/Invocation.cs, src/Testura.Code/Statements/ExceptionHandlingStatement.cs, src/Testura.Code/Statements/ExpressionStatement.cs, src/Testura.Code/Statements/Statement.cs, src/Testura.Code/Testura.Code.csproj
- Added generator for exception handling statements
- Added support for await with invocations
=> Exception handling statement
